### PR TITLE
Done - Fixing country selector bug

### PR DESCRIPTION
**Pull request by AlbertoCasasOrtiz**
* Done #30

### CODE REVIEW

**Comment by AlbertoCasasOrtiz** [comment]
@antoinefalisse Can you test if you are able to register using the new country selector? Also, please check that the step forward button works before merging.

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz I picked Belgium but it did not get saved:

image

**Comment by AlbertoCasasOrtiz** [comment]
I think it is working now, it is showing the country for my new user.

**Review by antoinefalisse — APPROVED** [review]

**Comment by antoinefalisse** [comment]
Great, thanks!

**Pull request merged**
