### PR TITLE
[DO NOT MERGE YET] dev

### PR DESCRIPTION
**Pull request by suhlrich**

### CODE REVIEW

**Comment by antoinefalisse** [comment]
@suhlrich and @AlbertoCasasOrtiz, just tried out and there is still a little delay sometimes. After discussing, we figured that not automatically playing the animation might solve the problem. @AlbertoCasasOrtiz will work on that. Thanks.

This session is a good one to try things out: https://dev.app.opencap.ai/session/98a97501-692e-4900-be59-dfa028e32aec

**Comment by suhlrich** [comment]
I do like the auto play function. Is there another solution? Perhaps we can discuss tomorrow

On Jan 30, 2023, at 5:06 PM, Antoine Falisse ***@***.***> wrote:

﻿

@suhlrich<https://github.com/suhlrich> and @AlbertoCasasOrtiz<https://github.com/AlbertoCasasOrtiz>, just tried out and there is still a little delay sometimes. After discussing, we figured that not automatically playing the animation might solve the problem. @AlbertoCasasOrtiz<https://github.com/AlbertoCasasOrtiz> will work on that. Thanks.

This session is a good one to try things out: https://dev.app.opencap.ai/session/98a97501-692e-4900-be59-dfa028e32aec

**Comment by AlbertoCasasOrtiz** [comment]
Sure, I think we should discuss this today. I let the link to the function that is probably causing this:

https://github.com/stanfordnmbl/opencap-viewer/blob/3ae194241f676dadba1e838ada4a610d0f997ccb/src/components/pages/Step5.vue#L672

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz is this PR ready to be merged? Should I test something?

**Pull request merged**
